# Permalinks
permalink: pretty

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Setup
title: Ember CLI Mirage
tagline: 'Develop and test your Ember app against a client-side server'
description: 'A client-side server to develop, test and prototype your Ember CLI app'
url: https://github.com/samselikoff/ember-cli-mirage
baseurl: ''
destination: jekyll-tmp/
exclude:
  - node_modules
  - bower_components
  - tmp

gems:
  - jekyll-redirect-from

github:
  repo: https://github.com/samselikoff/ember-cli-mirage

default_version: v0.2.x

defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
